import React from "react";
import {AbsoluteFill, Composition, Img, Sequence, interpolate, spring, useCurrentFrame} from "remotion";

const FPS = 30;
const TOTAL = 1362; // 45.4s voiceover
const RED = "#F20D2F";
const INK = "#0E0E0E";
const CREAM = "#F3EFE6";
const WHITE = "#FFFDF8";
const GRAY = "#A6A098";

const P1 = "https://images.pexels.com/photos/6936147/pexels-photo-6936147.jpeg?cs=srgb&dl=pexels-rdne-6936147.jpg&fm=jpg";
const P2 = "https://images.pexels.com/photos/7092370/pexels-photo-7092370.jpeg?cs=srgb&dl=pexels-rdne-7092370.jpg&fm=jpg";
const P3 = "https://images.pexels.com/photos/8419499/pexels-photo-8419499.jpeg?cs=srgb&dl=pexels-rdne-8419499.jpg&fm=jpg";
const P4 = "https://images.pexels.com/photos/8197498/pexels-photo-8197498.jpeg?cs=srgb&dl=pexels-yankrukov-8197498.jpg&fm=jpg";

const Brand = ({dark=false}:{dark?:boolean}) => <div style={{position:"absolute",left:64,right:64,bottom:72,display:"flex",justifyContent:"space-between",alignItems:"center",fontFamily:"Arial,Helvetica,sans-serif",color:dark?WHITE:INK,zIndex:50}}><div style={{fontSize:27,fontWeight:950,letterSpacing:2.4}}>HORS CADRE</div><div style={{fontSize:18,fontWeight:800,letterSpacing:1,opacity:.66}}>PENSE AUTREMENT.</div></div>;
const Source = ({dark=false}:{dark?:boolean}) => <div style={{position:"absolute",left:64,top:72,fontFamily:"Arial,Helvetica,sans-serif",fontSize:16,fontWeight:800,letterSpacing:1.5,color:dark?"rgba(255,255,255,.55)":"rgba(14,14,14,.48)",zIndex:45}}>SOURCE · ART. L511-5 · CODE DE L’ÉDUCATION</div>;
const Rule = () => <div style={{position:"absolute",left:64,top:112,width:118,height:8,borderRadius:99,background:RED,zIndex:45}}/>;

const Photo = ({src,shade=.46,pos="center"}:{src:string;shade?:number;pos?:string}) => {const f=useCurrentFrame(); return <AbsoluteFill style={{overflow:"hidden",background:INK}}><Img src={src} style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:pos,scale:interpolate(f,[0,180],[1.05,1.13],{extrapolateRight:"clamp"})}}/><AbsoluteFill style={{background:`linear-gradient(180deg,rgba(0,0,0,${shade*.5}),rgba(0,0,0,${shade}) 58%,rgba(0,0,0,${Math.min(.82,shade+.2)}))`}}/></AbsoluteFill>};
const Kicker = ({children,dark=false}:{children:React.ReactNode;dark?:boolean}) => <div style={{fontFamily:"Arial,Helvetica,sans-serif",fontSize:24,fontWeight:950,letterSpacing:3.2,textTransform:"uppercase",color:dark?WHITE:RED,marginBottom:18}}>{children}</div>;
const Big = ({children,dark=false,size=118}:{children:React.ReactNode;dark?:boolean;size?:number}) => <div style={{fontFamily:"Arial Black,Arial,Helvetica,sans-serif",fontSize:size,fontWeight:950,letterSpacing:-5.2,lineHeight:.9,textTransform:"uppercase",color:dark?WHITE:INK}}>{children}</div>;
const Small = ({children,dark=false}:{children:React.ReactNode;dark?:boolean}) => <div style={{fontFamily:"Arial,Helvetica,sans-serif",fontSize:31,lineHeight:1.22,fontWeight:760,color:dark?"rgba(255,255,255,.82)":"rgba(14,14,14,.7)",marginTop:26,maxWidth:880}}>{children}</div>;

const NotifyPhone = () => {const f=useCurrentFrame(); return <div style={{position:"absolute",right:88,top:455,width:360,height:710,borderRadius:58,background:"#151515",border:"12px solid #090909",boxShadow:"0 40px 95px rgba(0,0,0,.28)",overflow:"hidden",rotate:"-3deg"}}><div style={{width:128,height:36,borderRadius:99,background:"#030303",margin:"20px auto"}}/>{["12 NOTIFICATIONS","INSTAGRAM","TIKTOK","MESSAGES","SNAPCHAT"].map((t,i)=>{const p=interpolate(f,[i*7,i*7+16],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <div key={t} style={{margin:"15px 20px",height:72,borderRadius:18,background:i===0?RED:"#F5F2EC",translate:`${interpolate(p,[0,1],[330,0])}px 0`,opacity:p,display:"flex",alignItems:"center",padding:"0 18px",fontFamily:"Arial",fontWeight:950,fontSize:18,color:i===0?WHITE:INK}}>{t}</div>})}</div>};

const S1 = () => {const f=useCurrentFrame();const s=spring({frame:f,fps:FPS,config:{damping:14,stiffness:180}});return <AbsoluteFill style={{background:CREAM}}><Source/><Rule/><div style={{position:"absolute",left:64,top:200,width:630,zIndex:20,scale:.82+s*.18,transformOrigin:"left top"}}><Kicker>France · rentrée 2026</Kicker><Big size={150}>C’EST<br/>FINI.</Big><Small>Le téléphone change de statut au lycée.</Small></div><NotifyPhone/><Brand/></AbsoluteFill>};
const S2 = () => {const f=useCurrentFrame();return <AbsoluteFill><Photo src={P1} shade={.62} pos="55% center"/><Source dark/><Rule/><div style={{position:"absolute",left:64,top:220,width:930,zIndex:20,translate:`0 ${interpolate(f,[0,20],[80,0],{extrapolateRight:"clamp"})}px`}}><Kicker dark>Depuis le 1er septembre 2026</Kicker><Big dark size={108}>L’USAGE DU<br/>TÉLÉPHONE<br/><span style={{color:RED}}>EST INTERDIT.</span></Big><Small dark>Dans les lycées français, pendant le temps scolaire.</Small></div><Brand dark/></AbsoluteFill>};
const S3 = () => {const f=useCurrentFrame();const x=interpolate(f,[0,32],[58,0],{extrapolateRight:"clamp"});return <AbsoluteFill style={{background:WHITE}}><Img src={P2} style={{position:"absolute",right:0,top:0,width:540,height:1920,objectFit:"cover",objectPosition:"56% center"}}/><div style={{position:"absolute",right:0,top:0,width:620,height:1920,background:"linear-gradient(90deg,#fffdf8 0%,rgba(255,253,248,.92) 12%,rgba(255,253,248,.08) 100%)"}}/><Source/><Rule/><div style={{position:"absolute",left:64,top:240,width:670,zIndex:20,translate:`${x}px 0`}}><Kicker>Et pas seulement en cours</Kicker><Big size={98}>DANS TOUT<br/>LE TEMPS<br/><span style={{color:RED}}>SCOLAIRE.</span></Big><Small>Le principe vaut aussi pour les activités liées à l’enseignement hors de l’établissement.</Small></div><Brand/></AbsoluteFill>};
const S4 = () => {const f=useCurrentFrame();return <AbsoluteFill style={{background:CREAM}}><Source/><Rule/><div style={{position:"absolute",left:64,top:250,width:950}}><Kicker>Attention à la nuance</Kicker><div style={{display:"flex",alignItems:"center",gap:30,marginTop:32}}><div style={{fontFamily:"Arial Black",fontSize:108,fontWeight:950,lineHeight:.9}}>POSSÉDER</div><div style={{fontFamily:"Arial Black",fontSize:120,color:RED}}>≠</div></div><div style={{fontFamily:"Arial Black",fontSize:128,fontWeight:950,lineHeight:.9,marginTop:18}}>UTILISER.</div><Small>Le téléphone peut rester dans le sac. C’est son utilisation qui est interdite.</Small></div><div style={{position:"absolute",left:64,right:64,top:1130,height:360,border:`3px solid ${INK}`,borderRadius:28,overflow:"hidden"}}><div style={{position:"absolute",inset:0,background:INK}}/><div style={{position:"absolute",left:42,top:38,fontFamily:"Arial",fontSize:20,color:WHITE,fontWeight:900,letterSpacing:2}}>LE PRINCIPE EN UNE IMAGE</div><div style={{position:"absolute",left:42,bottom:42,fontFamily:"Arial Black",fontSize:66,color:WHITE,fontWeight:950}}>DANS LE SAC.<br/><span style={{color:RED}}>PAS DANS LA MAIN.</span></div><div style={{position:"absolute",right:42,top:68,width:170,height:280,borderRadius:30,border:`8px solid ${WHITE}`,rotate:`${interpolate(f,[0,70],[-9,3],{extrapolateRight:"clamp"})}deg`}}/></div><Brand/></AbsoluteFill>};
const S5 = () => {const f=useCurrentFrame();const p=spring({frame:f,fps:FPS,config:{damping:18,stiffness:120}});return <AbsoluteFill style={{background:INK}}><Source dark/><Rule/><div style={{position:"absolute",left:64,top:220,width:930}}><Kicker dark>Mais pas sans exception</Kicker><Big dark size={110}>DES EXCEPTIONS<br/><span style={{color:RED}}>EXISTENT.</span></Big><Small dark>Elles sont définies par le règlement intérieur, avec des cas particuliers prévus par la loi.</Small></div><div style={{position:"absolute",left:90,right:90,top:980,height:470,background:WHITE,borderRadius:28,rotate:`${-2+p*2}deg`,boxShadow:"0 34px 80px rgba(0,0,0,.35)",padding:"42px 48px",boxSizing:"border-box"}}><div style={{fontFamily:"Arial",fontSize:18,fontWeight:900,letterSpacing:2,color:GRAY}}>RÈGLEMENT INTÉRIEUR</div><div style={{height:8,width:120,background:RED,borderRadius:99,margin:"24px 0 30px"}}/><div style={{fontFamily:"Arial Black",fontSize:57,fontWeight:950,lineHeight:1.02,color:INK}}>LES MODALITÉS<br/>SONT FIXÉES<br/>PAR L’ÉTABLISSEMENT.</div></div><Brand dark/></AbsoluteFill>};
const S6 = () => {const f=useCurrentFrame();const ws=["ATTENTION.","CONCENTRATION.","ÉCRANS."];return <AbsoluteFill style={{background:CREAM}}><Source/><Rule/><div style={{position:"absolute",left:64,top:220,width:950}}><Kicker>Pourquoi cette décision ?</Kicker>{ws.map((w,i)=>{const p=interpolate(f,[i*16,i*16+14],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <div key={w} style={{fontFamily:"Arial Black",fontSize:i===1?100:126,fontWeight:950,letterSpacing:-5,lineHeight:1,color:i===2?RED:INK,translate:`${interpolate(p,[0,1],[-100,0])}px 0`,opacity:p,marginBottom:9}}>{w}</div>})}<Small>Le ministère met en avant la surexposition aux écrans et la capacité d’attention des élèves.</Small></div><Brand/></AbsoluteFill>};
const S7 = () => {const f=useCurrentFrame();return <AbsoluteFill><Photo src={P2} shade={.72} pos="50% center"/><Source dark/><Rule/><div style={{position:"absolute",left:64,top:235,width:930,zIndex:20}}><Kicker dark>Si la règle n’est pas respectée</Kicker><Big dark size={118}>CONFISCATION<br/><span style={{color:RED}}>POSSIBLE.</span></Big><Small dark>Le règlement intérieur fixe les modalités de confiscation et de restitution.</Small></div><div style={{position:"absolute",right:72,bottom:260,width:300,height:300,border:`5px solid ${RED}`,borderRadius:"50%",scale:interpolate(f,[0,26],[.5,1],{extrapolateRight:"clamp"}),opacity:interpolate(f,[0,20],[0,.8],{extrapolateRight:"clamp"})}}/><Brand dark/></AbsoluteFill>};
const S8 = () => {const f=useCurrentFrame();const cut=interpolate(f,[8,70],[30,76],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <AbsoluteFill style={{background:INK,overflow:"hidden"}}><Img src={P1} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/><div style={{position:"absolute",inset:0,width:`${cut}%`,overflow:"hidden"}}><Img src={P3} style={{position:"absolute",left:0,top:0,width:1080,height:1920,objectFit:"cover"}}/></div><div style={{position:"absolute",left:`${cut}%`,top:0,bottom:0,width:8,background:RED,translate:"-4px 0"}}/><AbsoluteFill style={{background:"linear-gradient(180deg,rgba(0,0,0,.12),transparent 48%,rgba(0,0,0,.78))"}}/><Source dark/><div style={{position:"absolute",left:64,bottom:250,width:930,zIndex:20}}><Kicker dark>L’objectif affiché</Kicker><Big dark size={101}>MOINS D’ÉCRAN.<br/><span style={{color:RED}}>PLUS D’ÉCHANGES.</span></Big></div><Brand dark/></AbsoluteFill>};
const S9 = () => {const f=useCurrentFrame();const p=spring({frame:f,fps:FPS,config:{damping:16,stiffness:135}});return <AbsoluteFill style={{background:CREAM}}><Source/><Rule/><div style={{position:"absolute",left:64,top:245,width:950,scale:.9+p*.1,transformOrigin:"left center"}}><Kicker>Alors…</Kicker><Big size={122}>MESURE<br/>NÉCESSAIRE…<br/><span style={{color:RED}}>OU TROP LOIN ?</span></Big><Small>La règle est posée. Le débat, lui, commence maintenant.</Small></div><div style={{position:"absolute",left:64,right:64,bottom:235,borderTop:`4px solid ${INK}`,paddingTop:24,fontFamily:"Arial",fontSize:29,fontWeight:950,letterSpacing:1.4}}>À TOI DE TRANCHER ↓</div><Brand/></AbsoluteFill>};

const Flash = () => {const f=useCurrentFrame();const cuts=[198,344,504,642,776,934,1107,1276];const d=cuts.reduce((m,c)=>Math.min(m,Math.abs(f-c)),999);return <AbsoluteFill style={{pointerEvents:"none",zIndex:100,background:`rgba(255,255,255,${interpolate(d,[0,1,4],[.22,.08,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})})`}}/>};
const Grain = () => {const f=useCurrentFrame();return <AbsoluteFill style={{pointerEvents:"none",zIndex:90,opacity:.075,mixBlendMode:"multiply",backgroundImage:"radial-gradient(circle,rgba(0,0,0,.25) 0 1px,transparent 1.2px)",backgroundSize:"11px 11px",backgroundPosition:`${(f*7)%23}px ${(f*5)%19}px`}}/>};

export const PhoneBan2026V2Video:React.FC=()=> <AbsoluteFill style={{background:CREAM}}>
  <Sequence from={0} durationInFrames={198}><S1/></Sequence>
  <Sequence from={198} durationInFrames={146}><S2/></Sequence>
  <Sequence from={344} durationInFrames={160}><S3/></Sequence>
  <Sequence from={504} durationInFrames={138}><S4/></Sequence>
  <Sequence from={642} durationInFrames={134}><S5/></Sequence>
  <Sequence from={776} durationInFrames={158}><S6/></Sequence>
  <Sequence from={934} durationInFrames={173}><S7/></Sequence>
  <Sequence from={1107} durationInFrames={169}><S8/></Sequence>
  <Sequence from={1276} durationInFrames={86}><S9/></Sequence>
  <Grain/><Flash/>
</AbsoluteFill>;

export const PhoneBan2026V2Composition:React.FC=()=> <Composition id="PhoneBan2026V2" component={PhoneBan2026V2Video} durationInFrames={TOTAL} fps={FPS} width={1080} height={1920}/>;
