import React from "react";
import {AbsoluteFill, Composition, Img, Sequence, interpolate, spring, useCurrentFrame} from "remotion";

const FPS = 30;
const TOTAL = 1362;
const RED = "#F20D2F";
const INK = "#0E0E0E";
const CREAM = "#F3EFE6";
const WHITE = "#FFFDF8";
const GRAY = "#A6A098";

const P1 = "https://images.pexels.com/photos/6936147/pexels-photo-6936147.jpeg?cs=srgb&dl=pexels-rdne-6936147.jpg&fm=jpg";
const P2 = "https://images.pexels.com/photos/7092370/pexels-photo-7092370.jpeg?cs=srgb&dl=pexels-rdne-7092370.jpg&fm=jpg";
const P3 = "https://images.pexels.com/photos/8419499/pexels-photo-8419499.jpeg?cs=srgb&dl=pexels-rdne-8419499.jpg&fm=jpg";
const P4 = "https://images.pexels.com/photos/8197498/pexels-photo-8197498.jpeg?cs=srgb&dl=pexels-yankrukov-8197498.jpg&fm=jpg";

const Brand = ({dark=false}:{dark?:boolean}) => <div style={{position:"absolute",left:64,right:64,bottom:72,display:"flex",justifyContent:"space-between",alignItems:"center",fontFamily:"Arial,Helvetica,sans-serif",color:dark?WHITE:INK,zIndex:50}}><div style={{fontSize:27,fontWeight:950,letterSpacing:2.4}}>HORS CADRE</div><div style={{fontSize:18,fontWeight:800,letterSpacing:1,opacity:.66}}>PENSE AUTREMENT.</div></div>;
const Source = ({dark=false}:{dark?:boolean}) => <div style={{position:"absolute",left:64,top:72,fontFamily:"Arial,Helvetica,sans-serif",fontSize:16,fontWeight:800,letterSpacing:1.5,color:dark?"rgba(255,255,255,.55)":"rgba(14,14,14,.48)",zIndex:45}}>SOURCE · ART. L511-5 · CODE DE L’ÉDUCATION</div>;
const Rule = () => <div style={{position:"absolute",left:64,top:112,width:118,height:8,borderRadius:99,background:RED,zIndex:45}}/>;
const Kicker = ({children,dark=false}:{children:React.ReactNode;dark?:boolean}) => <div style={{fontFamily:"Arial,Helvetica,sans-serif",fontSize:24,fontWeight:950,letterSpacing:3.2,textTransform:"uppercase",color:dark?WHITE:RED,marginBottom:18}}>{children}</div>;
const Big = ({children,dark=false,size=118}:{children:React.ReactNode;dark?:boolean;size?:number}) => <div style={{fontFamily:"Arial Black,Arial,Helvetica,sans-serif",fontSize:size,fontWeight:950,letterSpacing:-5.2,lineHeight:.9,textTransform:"uppercase",color:dark?WHITE:INK}}>{children}</div>;
const Small = ({children,dark=false}:{children:React.ReactNode;dark?:boolean}) => <div style={{fontFamily:"Arial,Helvetica,sans-serif",fontSize:31,lineHeight:1.22,fontWeight:760,color:dark?"rgba(255,255,255,.84)":"rgba(14,14,14,.72)",marginTop:26,maxWidth:880}}>{children}</div>;
const Tag = ({children,dark=false}:{children:React.ReactNode;dark?:boolean}) => <div style={{display:"inline-flex",alignItems:"center",padding:"12px 18px",border:`2px solid ${dark?WHITE:INK}`,borderRadius:999,fontFamily:"Arial",fontSize:18,fontWeight:950,letterSpacing:1.4,color:dark?WHITE:INK,background:dark?"rgba(0,0,0,.15)":"rgba(255,255,255,.35)",marginRight:10,marginTop:14}}>{children}</div>;
const Photo = ({src,shade=.46,pos="center",zoom=1.09}:{src:string;shade?:number;pos?:string;zoom?:number}) => {const f=useCurrentFrame(); return <AbsoluteFill style={{overflow:"hidden",background:INK}}><Img src={src} style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:pos,scale:interpolate(f,[0,180],[zoom,zoom+.10],{extrapolateRight:"clamp"})}}/><AbsoluteFill style={{background:`linear-gradient(180deg,rgba(0,0,0,${shade*.42}),rgba(0,0,0,${shade}) 58%,rgba(0,0,0,${Math.min(.86,shade+.22)}))`}}/></AbsoluteFill>};

const MiniStat = ({label,value,dark=false}:{label:string;value:string;dark?:boolean}) => <div style={{width:220,padding:"18px 20px",borderRadius:20,background:dark?"rgba(255,255,255,.10)":"rgba(14,14,14,.06)",border:`1px solid ${dark?"rgba(255,255,255,.22)":"rgba(14,14,14,.12)"}`}}><div style={{fontFamily:"Arial",fontSize:14,fontWeight:900,letterSpacing:1.6,color:dark?"rgba(255,255,255,.6)":GRAY}}>{label}</div><div style={{fontFamily:"Arial Black",fontSize:29,fontWeight:950,color:dark?WHITE:INK,marginTop:6}}>{value}</div></div>;

const NotifyPhone = () => {const f=useCurrentFrame(); return <><div style={{position:"absolute",left:575,top:280,width:390,height:790,borderRadius:64,background:"#151515",border:"12px solid #090909",boxShadow:"0 44px 110px rgba(0,0,0,.33)",overflow:"hidden",rotate:"-3deg"}}><div style={{width:132,height:38,borderRadius:99,background:"#030303",margin:"20px auto"}}/>{["12 NOTIFICATIONS","INSTAGRAM","TIKTOK","MESSAGES","SNAPCHAT"].map((t,i)=>{const p=interpolate(f,[i*7,i*7+16],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <div key={t} style={{margin:"15px 20px",height:74,borderRadius:18,background:i===0?RED:"#F5F2EC",translate:`${interpolate(p,[0,1],[360,0])}px 0`,opacity:p,display:"flex",alignItems:"center",padding:"0 18px",fontFamily:"Arial",fontWeight:950,fontSize:18,color:i===0?WHITE:INK}}>{t}</div>})}</div><div style={{position:"absolute",left:620,top:1100,width:300,display:"flex",gap:10,flexWrap:"wrap"}}><Tag>LYCÉE</Tag><Tag>RENTRÉE 2026</Tag><Tag>FRANCE</Tag></div></>};

const S1 = () => {const f=useCurrentFrame();const s=spring({frame:f,fps:FPS,config:{damping:14,stiffness:180}});return <AbsoluteFill style={{background:CREAM}}><Source/><Rule/><div style={{position:"absolute",left:64,top:180,width:560,zIndex:20,scale:.82+s*.18,transformOrigin:"left top"}}><Kicker>France · rentrée 2026</Kicker><Big size={154}>C’EST<br/>FINI.</Big><Small>Le téléphone change de statut au lycée.</Small><div style={{display:"flex",gap:12,marginTop:26}}><MiniStat label="RÈGLE" value="NATIONALE"/><MiniStat label="DEPUIS" value="01.09.26"/></div></div><NotifyPhone/><div style={{position:"absolute",left:64,right:64,top:1480,height:1,background:"rgba(14,14,14,.18)"}}/><div style={{position:"absolute",left:64,top:1510,fontFamily:"Arial",fontSize:22,fontWeight:900,letterSpacing:1.4,color:INK}}>LE TÉLÉPHONE RESTE POSSIBLE · SON USAGE CHANGE</div><Brand/></AbsoluteFill>};

const S2 = () => {const f=useCurrentFrame();return <AbsoluteFill><Photo src={P1} shade={.58} pos="52% center" zoom={1.15}/><Source dark/><Rule/><div style={{position:"absolute",left:64,top:205,width:920,zIndex:20,translate:`0 ${interpolate(f,[0,20],[70,0],{extrapolateRight:"clamp"})}px`}}><Kicker dark>Depuis le 1er septembre 2026</Kicker><Big dark size={106}>L’USAGE DU<br/>TÉLÉPHONE<br/><span style={{color:RED}}>EST INTERDIT.</span></Big><Small dark>Dans les lycées français, pendant le temps scolaire.</Small><div style={{display:"flex",gap:12,marginTop:28}}><MiniStat dark label="LIEU" value="LYCÉE"/><MiniStat dark label="PÉRIODE" value="TEMPS SCOLAIRE"/></div></div><div style={{position:"absolute",right:70,bottom:250,width:250,height:250,border:`4px solid ${RED}`,borderRadius:"50%",opacity:.65}}/><Brand dark/></AbsoluteFill>};

const S3 = () => {const f=useCurrentFrame();const x=interpolate(f,[0,32],[58,0],{extrapolateRight:"clamp"});return <AbsoluteFill style={{background:WHITE}}><Img src={P2} style={{position:"absolute",right:0,top:0,width:575,height:1920,objectFit:"cover",objectPosition:"56% center",scale:1.09}}/><div style={{position:"absolute",right:0,top:0,width:650,height:1920,background:"linear-gradient(90deg,#fffdf8 0%,rgba(255,253,248,.88) 14%,rgba(255,253,248,.04) 100%)"}}/><Source/><Rule/><div style={{position:"absolute",left:64,top:225,width:680,zIndex:20,translate:`${x}px 0`}}><Kicker>Et pas seulement en cours</Kicker><Big size={96}>DANS TOUT<br/>LE TEMPS<br/><span style={{color:RED}}>SCOLAIRE.</span></Big><Small>Le principe vaut aussi pour les activités liées à l’enseignement hors de l’établissement.</Small><div><Tag>COURS</Tag><Tag>COULOIRS</Tag><Tag>SORTIES</Tag></div></div><div style={{position:"absolute",left:64,top:1280,width:520,height:250,border:`2px solid rgba(14,14,14,.16)`,borderRadius:26,padding:"30px 32px",boxSizing:"border-box",background:"rgba(255,255,255,.82)"}}><div style={{fontFamily:"Arial",fontSize:16,fontWeight:900,letterSpacing:1.7,color:GRAY}}>À RETENIR</div><div style={{fontFamily:"Arial Black",fontSize:42,fontWeight:950,lineHeight:1.05,marginTop:16}}>LA RÈGLE SUIT<br/><span style={{color:RED}}>LE TEMPS SCOLAIRE.</span></div></div><Brand/></AbsoluteFill>};

const S4 = () => {const f=useCurrentFrame();return <AbsoluteFill style={{background:CREAM}}><Source/><Rule/><div style={{position:"absolute",left:64,top:220,width:950}}><Kicker>Attention à la nuance</Kicker><div style={{display:"flex",alignItems:"center",gap:28,marginTop:28}}><div style={{fontFamily:"Arial Black",fontSize:108,fontWeight:950,lineHeight:.9}}>POSSÉDER</div><div style={{fontFamily:"Arial Black",fontSize:120,color:RED}}>≠</div></div><div style={{fontFamily:"Arial Black",fontSize:128,fontWeight:950,lineHeight:.9,marginTop:18}}>UTILISER.</div><Small>Le téléphone peut rester dans le sac. C’est son utilisation qui est interdite.</Small></div><div style={{position:"absolute",left:64,right:64,top:1020,height:520,border:`3px solid ${INK}`,borderRadius:30,overflow:"hidden",display:"flex"}}><div style={{width:"50%",background:INK,position:"relative"}}><div style={{position:"absolute",left:34,top:32,fontFamily:"Arial",fontSize:16,fontWeight:900,letterSpacing:1.7,color:WHITE}}>AUTORISÉ</div><div style={{position:"absolute",left:34,bottom:36,fontFamily:"Arial Black",fontSize:48,fontWeight:950,lineHeight:1.02,color:WHITE}}>DANS<br/>LE SAC.</div><div style={{position:"absolute",right:46,top:116,width:150,height:255,borderRadius:28,border:`7px solid ${WHITE}`,rotate:`${interpolate(f,[0,70],[-8,2],{extrapolateRight:"clamp"})}deg`,opacity:.85}}/></div><div style={{width:"50%",background:WHITE,position:"relative"}}><div style={{position:"absolute",left:34,top:32,fontFamily:"Arial",fontSize:16,fontWeight:900,letterSpacing:1.7,color:RED}}>INTERDIT</div><div style={{position:"absolute",left:34,bottom:36,fontFamily:"Arial Black",fontSize:48,fontWeight:950,lineHeight:1.02,color:INK}}>DANS<br/><span style={{color:RED}}>LA MAIN.</span></div><div style={{position:"absolute",right:42,top:110,width:160,height:280,borderRadius:30,border:`8px solid ${INK}`,rotate:`${interpolate(f,[0,70],[7,-2],{extrapolateRight:"clamp"})}deg`}}/></div></div><Brand/></AbsoluteFill>};

const S5 = () => {const f=useCurrentFrame();const p=spring({frame:f,fps:FPS,config:{damping:18,stiffness:120}});return <AbsoluteFill style={{background:INK}}><Source dark/><Rule/><div style={{position:"absolute",left:64,top:205,width:930}}><Kicker dark>Mais pas sans exception</Kicker><Big dark size={108}>DES EXCEPTIONS<br/><span style={{color:RED}}>EXISTENT.</span></Big><Small dark>Elles sont définies par le règlement intérieur, avec des cas particuliers prévus par la loi.</Small></div><div style={{position:"absolute",left:62,right:62,top:900,height:610,background:WHITE,borderRadius:28,rotate:`${-2+p*2}deg`,boxShadow:"0 34px 80px rgba(0,0,0,.35)",padding:"42px 48px",boxSizing:"border-box"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontFamily:"Arial",fontSize:18,fontWeight:900,letterSpacing:2,color:GRAY}}>RÈGLEMENT INTÉRIEUR</div><div style={{fontFamily:"Arial",fontSize:14,fontWeight:900,color:RED}}>DOCUMENT ÉTABLISSEMENT</div></div><div style={{height:8,width:120,background:RED,borderRadius:99,margin:"24px 0 28px"}}/><div style={{fontFamily:"Arial Black",fontSize:56,fontWeight:950,lineHeight:1.02,color:INK}}>LES MODALITÉS<br/>SONT FIXÉES<br/>PAR L’ÉTABLISSEMENT.</div><div style={{marginTop:34}}><div style={{height:14,width:"86%",background:"rgba(14,14,14,.09)",borderRadius:9,marginBottom:14}}/><div style={{height:14,width:"74%",background:"rgba(14,14,14,.09)",borderRadius:9,marginBottom:14}}/><div style={{height:14,width:"91%",background:"rgba(14,14,14,.09)",borderRadius:9,marginBottom:14}}/><div style={{height:14,width:"62%",background:RED,borderRadius:9,opacity:.8}}/></div><div style={{position:"absolute",right:40,bottom:40,border:`3px solid ${RED}`,borderRadius:999,padding:"14px 20px",fontFamily:"Arial",fontSize:16,fontWeight:950,color:RED,rotate:"-7deg"}}>CAS PARTICULIERS</div></div><Brand dark/></AbsoluteFill>};

const S6 = () => {const f=useCurrentFrame();const ws=["ATTENTION.","CONCENTRATION.","ÉCRANS."];return <AbsoluteFill style={{background:CREAM}}><Source/><Rule/><div style={{position:"absolute",left:64,top:200,width:950}}><Kicker>Pourquoi cette décision ?</Kicker>{ws.map((w,i)=>{const p=interpolate(f,[i*16,i*16+14],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <div key={w} style={{fontFamily:"Arial Black",fontSize:i===1?100:126,fontWeight:950,letterSpacing:-5,lineHeight:1,color:i===2?RED:INK,translate:`${interpolate(p,[0,1],[-100,0])}px 0`,opacity:p,marginBottom:9}}>{w}</div>})}<Small>Le ministère met en avant la surexposition aux écrans et la capacité d’attention des élèves.</Small><div style={{display:"flex",gap:12,marginTop:28,flexWrap:"wrap"}}><Tag>SUREXPOSITION</Tag><Tag>DISTRACTION</Tag><Tag>CONCENTRATION</Tag></div></div><div style={{position:"absolute",right:70,bottom:230,width:280,height:420,borderRadius:28,border:`2px solid rgba(14,14,14,.18)`,padding:"28px 24px",boxSizing:"border-box",background:"rgba(255,255,255,.5)"}}><div style={{fontFamily:"Arial",fontSize:16,fontWeight:900,letterSpacing:1.4,color:GRAY}}>TEMPS D’ÉCRAN</div>{[68,91,54,78,46].map((h,i)=><div key={i} style={{height:44,marginTop:18,borderRadius:10,background:"rgba(14,14,14,.06)",overflow:"hidden"}}><div style={{height:"100%",width:`${h}%`,background:i===1?RED:INK,opacity:i===1?1:.72}}/></div>)}</div><Brand/></AbsoluteFill>};

const S7 = () => {const f=useCurrentFrame();return <AbsoluteFill><Photo src={P2} shade={.68} pos="50% center" zoom={1.18}/><Source dark/><Rule/><div style={{position:"absolute",left:64,top:220,width:930,zIndex:20}}><Kicker dark>Si la règle n’est pas respectée</Kicker><Big dark size={116}>CONFISCATION<br/><span style={{color:RED}}>POSSIBLE.</span></Big><Small dark>Le règlement intérieur fixe les modalités de confiscation et de restitution.</Small><div><Tag dark>SI LA RÈGLE N’EST PAS RESPECTÉE</Tag></div></div><div style={{position:"absolute",right:70,bottom:260,width:360,height:360,border:`6px solid ${RED}`,borderRadius:"50%",scale:interpolate(f,[0,26],[.5,1],{extrapolateRight:"clamp"}),opacity:interpolate(f,[0,20],[0,.9],{extrapolateRight:"clamp"})}}/><div style={{position:"absolute",right:30,bottom:620,fontFamily:"Arial",fontSize:16,fontWeight:900,letterSpacing:1.4,color:WHITE,rotate:"90deg",opacity:.65}}>MESURE DISCIPLINAIRE</div><Brand dark/></AbsoluteFill>};

const S8 = () => {const f=useCurrentFrame();const cut=interpolate(f,[8,70],[26,76],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <AbsoluteFill style={{background:INK,overflow:"hidden"}}><Img src={P1} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",scale:1.08}}/><div style={{position:"absolute",inset:0,width:`${cut}%`,overflow:"hidden"}}><Img src={P3} style={{position:"absolute",left:0,top:0,width:1080,height:1920,objectFit:"cover",scale:1.08}}/></div><div style={{position:"absolute",left:`${cut}%`,top:0,bottom:0,width:8,background:RED,translate:"-4px 0"}}/><AbsoluteFill style={{background:"linear-gradient(180deg,rgba(0,0,0,.12),transparent 44%,rgba(0,0,0,.82))"}}/><Source dark/><div style={{position:"absolute",left:64,bottom:260,width:930,zIndex:20}}><Kicker dark>L’objectif affiché</Kicker><Big dark size={101}>MOINS D’ÉCRAN.<br/><span style={{color:RED}}>PLUS D’ÉCHANGES.</span></Big><div style={{marginTop:22}}><Tag dark>PRÉSENCE</Tag><Tag dark>ÉCHANGE</Tag><Tag dark>ATTENTION</Tag></div></div><div style={{position:"absolute",left:64,top:200,fontFamily:"Arial",fontSize:17,fontWeight:950,letterSpacing:2,color:WHITE,opacity:.68}}>ÉCRAN</div><div style={{position:"absolute",right:64,top:200,fontFamily:"Arial",fontSize:17,fontWeight:950,letterSpacing:2,color:WHITE,opacity:.68}}>ÉCHANGES</div><Brand dark/></AbsoluteFill>};

const S9 = () => {const f=useCurrentFrame();const p=spring({frame:f,fps:FPS,config:{damping:16,stiffness:135}});return <AbsoluteFill style={{background:CREAM}}><Source/><Rule/><div style={{position:"absolute",left:64,top:220,width:950,scale:.9+p*.1,transformOrigin:"left center"}}><Kicker>Alors…</Kicker><Big size={122}>MESURE<br/>NÉCESSAIRE…<br/><span style={{color:RED}}>OU TROP LOIN ?</span></Big><Small>La règle est posée. Le débat, lui, commence maintenant.</Small><div style={{display:"flex",gap:14,marginTop:30}}><Tag>PROTÉGER</Tag><Tag>CONTRÔLER</Tag></div></div><div style={{position:"absolute",right:90,top:1110,width:220,height:390,border:`9px solid ${INK}`,borderRadius:38,rotate:"8deg",opacity:.08}}/><div style={{position:"absolute",left:64,right:64,bottom:235,borderTop:`4px solid ${INK}`,paddingTop:24,fontFamily:"Arial",fontSize:29,fontWeight:950,letterSpacing:1.4}}>À TOI DE TRANCHER ↓</div><Brand/></AbsoluteFill>};

const Flash = () => {const f=useCurrentFrame();const cuts=[198,344,504,642,776,934,1107,1276];const d=cuts.reduce((m,c)=>Math.min(m,Math.abs(f-c)),999);return <AbsoluteFill style={{pointerEvents:"none",zIndex:100,background:`rgba(255,255,255,${interpolate(d,[0,1,4],[.22,.08,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})})`}}/>};
const Grain = () => {const f=useCurrentFrame();return <AbsoluteFill style={{pointerEvents:"none",zIndex:90,opacity:.075,mixBlendMode:"multiply",backgroundImage:"radial-gradient(circle,rgba(0,0,0,.25) 0 1px,transparent 1.2px)",backgroundSize:"11px 11px",backgroundPosition:`${(f*7)%23}px ${(f*5)%19}px`}}/>};

export const PhoneBan2026V21Video:React.FC=()=> <AbsoluteFill style={{background:CREAM}}>
  <Sequence from={0} durationInFrames={198}><S1/></Sequence>
  <Sequence from={198} durationInFrames={146}><S2/></Sequence>
  <Sequence from={344} durationInFrames={160}><S3/></Sequence>
  <Sequence from={504} durationInFrames={138}><S4/></Sequence>
  <Sequence from={642} durationInFrames={134}><S5/></Sequence>
  <Sequence from={776} durationInFrames={158}><S6/></Sequence>
  <Sequence from={934} durationInFrames={173}><S7/></Sequence>
  <Sequence from={1107} durationInFrames={169}><S8/></Sequence>
  <Sequence from={1276} durationInFrames={86}><S9/></Sequence>
  <Grain/><Flash/>
</AbsoluteFill>;

export const PhoneBan2026V21Composition:React.FC=()=> <Composition id="PhoneBan2026V21" component={PhoneBan2026V21Video} durationInFrames={TOTAL} fps={FPS} width={1080} height={1920}/>;